spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 15 #最大连接数
      auto-commit: true
      connection-timeout: 30000 # 最大毫秒数
      max-lifetime: 1800000 # 关闭后最长生命周期
      connection-test-query: select 1
      idle-timeout: 300000 # 空闲最长时间
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: ${spring.application.name}
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070